# 基础镜像使用java
FROM openjdk:11-jre
# 作者
MAINTAINER zhuhodor <zhd30@outlook.com>
# VOLUME 指定了临时文件目录为/tmp。
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp
# 将jar包添加到容器中并更名为app.jar
ADD ../pets-server/target/pets-server-0.0.1-SNAPSHOT.jar pets.jar
# 运行jar包
RUN bash -c 'touch /pets.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","--add-opens","java.base/java.lang=ALL-UNNAMED",\
"--add-opens","java.base/java.util=ALL-UNNAMED","--add-opens","java.desktop/java.awt.font=ALL-UNNAMED",\
 "-jar","/pets.jar",\
 "--spring.profiles.active=own"]

