version: "3"

#服务容器
services:
  petsBackService:
    image: pets-server:0.1
    container_name: pets-back
    ports:
      - "8888:8888"
    volumes:
      - ./data/appdata:/data
    networks:
      - dormhub_net
    depends_on:
      - redis
      - mysql
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data/data:/data
      - ./data/redis_data/redis.conf:/etc/redis/redis.conf
    networks:
      - dormhub_net
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '20001030'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'pets'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '20001030'
    ports:
    - "3306:3306"
    volumes:
    - ./data/mysql_data/db:/var/lib/mysql
    - ./data/mysql_data/conf/my.cnf:/etc/my.cnf
    - ./data/mysql_data/init:/docker-entrypoint-initdb.d
    networks:
      - dormhub_net
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: rabbitmq:3.8.11
    networks:
      - dormhub_net
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
    - ./data/rabbit_data/data:/var/lib/rabbitmq


networks:
  dormhub_net:
