server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pets?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 20001030
    username: root
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 100000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 100000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 49.235.92.49
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 20001030
    timeout: 3000ms # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

  #  rabbitmq:
  #    host: 49.235.92.49
  #    port: 5672
  #    username: zhu
  #    password: admin
  #    virtual-host: /dorm
  #    #    确认回调
  #    publisher-confirm-type: correlated
  #    #    失败回调
  #    publisher-returns: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: com.zhuhodor.server.model.pojo
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
  level:
    com.zhuhodor.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: petsrect
  expiration: 684888
  tokenHead: Bearer

cos:
  secretId: AKIDqrb6Wa90mwqVw9OFerBFE4ez3uZ0LpoW
  secretKey: qT7amjO5ZprcEZfUGqhZkETecJ5c37uw
  regionAddr: ap-nanjing
  bucketName: mybase-1-1305081850
  remoteAddr: https://mybase-1-1305081850.cos.ap-nanjing.myqcloud.com/
